export enum RouteNames {
  HOME = 'HOME',
  DASHBOARD = 'DASHBOARD',
  DASHBOARD_CHAT = 'DASHBOARD_CHAT',
  DASHBOARD_ADMIN = 'DASHBOARD_ADMIN',
}

export enum SessionStorageKeys {
  SESSION = 'SIMPLECHATSESSIONID',
}

export enum Errors {
  ERROR_MISSING_NICKNAME = 'ERROR_MISSING_NICKNAME',
  ERROR_NICKNAME_IN_USE = 'ERROR_NICKNAME_IN_USE',
}
